// Mocks generated by Mockito 5.4.6 from annotations
// in okada_vet_clinic/test/modules/medical_cases/controllers/case_form_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:okada_vet_clinic/data/models/customer_model.dart' as _i7;
import 'package:okada_vet_clinic/data/models/medical_case_model.dart' as _i6;
import 'package:okada_vet_clinic/data/models/pet_model.dart' as _i8;
import 'package:okada_vet_clinic/data/models/service_model.dart' as _i9;
import 'package:okada_vet_clinic/services/pdf_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PdfService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfService extends _i1.Mock implements _i3.PdfService {
  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<_i5.Uint8List> generateMedicalCasePdf({
    required _i6.MedicalCaseModel? medicalCase,
    required _i7.CustomerModel? customer,
    required _i8.PetModel? pet,
    required List<_i9.CaseServiceModel>? services,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateMedicalCasePdf, [], {
              #medicalCase: medicalCase,
              #customer: customer,
              #pet: pet,
              #services: services,
            }),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
            returnValueForMissingStub: _i4.Future<_i5.Uint8List>.value(
              _i5.Uint8List(0),
            ),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<void> printMedicalCase({
    required _i6.MedicalCaseModel? medicalCase,
    required _i7.CustomerModel? customer,
    required _i8.PetModel? pet,
    required List<_i9.CaseServiceModel>? services,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#printMedicalCase, [], {
              #medicalCase: medicalCase,
              #customer: customer,
              #pet: pet,
              #services: services,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> shareMedicalCase({
    required _i6.MedicalCaseModel? medicalCase,
    required _i7.CustomerModel? customer,
    required _i8.PetModel? pet,
    required List<_i9.CaseServiceModel>? services,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareMedicalCase, [], {
              #medicalCase: medicalCase,
              #customer: customer,
              #pet: pet,
              #services: services,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Uint8List> generateInvoicePdf({
    required _i6.MedicalCaseModel? medicalCase,
    required _i7.CustomerModel? customer,
    required _i8.PetModel? pet,
    required List<_i9.CaseServiceModel>? services,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateInvoicePdf, [], {
              #medicalCase: medicalCase,
              #customer: customer,
              #pet: pet,
              #services: services,
            }),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
            returnValueForMissingStub: _i4.Future<_i5.Uint8List>.value(
              _i5.Uint8List(0),
            ),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<void> printInvoice({
    required _i6.MedicalCaseModel? medicalCase,
    required _i7.CustomerModel? customer,
    required _i8.PetModel? pet,
    required List<_i9.CaseServiceModel>? services,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#printInvoice, [], {
              #medicalCase: medicalCase,
              #customer: customer,
              #pet: pet,
              #services: services,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> shareInvoice({
    required _i6.MedicalCaseModel? medicalCase,
    required _i7.CustomerModel? customer,
    required _i8.PetModel? pet,
    required List<_i9.CaseServiceModel>? services,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareInvoice, [], {
              #medicalCase: medicalCase,
              #customer: customer,
              #pet: pet,
              #services: services,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
